### ISSUE TITLE
Errors in example on documentation front page.

### ISSUE THREAD

**Issue by AndreLouisCaron** [bbangert/routes#1]
The [documentation front page](http://routes.readthedocs.org/en/latest/index.html) on Read the Docs contains an example of `routes` usage but this example contains two errors.

---

First, the following snippet is missing a double-quote before the comma:

     map.connect(None, "/error/{action}/{id}, controller="error")

It probably should read like the following (note that this will fix the syntax highlighting):

     map.connect(None, "/error/{action}/{id}", controller="error")

---

Second, the following snippet should probably read `'controller': 'error'` to match the mapping.

    # result == {'controller': 'main', 'action': 'myapp', 'id': '4'}

It should read like the following since it matches the `map.connect(..., controller="error")` pattern.

    # result == {'controller': 'error', 'action': 'myapp', 'id': '4'}

~~On a side note, it might be interesting to explain why the `action` is set to `myapp`, perhaps this is the default?~~

**Comment by bbangert** [comment]
Fixed.
