### ISSUE TITLE
Wrong error code returned

### ISSUE THREAD

**Issue by sdekrijger** [bbangert/routes#16]
When using an undefined method (i.e. the used method's name is not in the list of methods assigned to the method key in the dictionary passed to conditions in a connect fcn call) the error returned is 404 Not Found while it should be 405 Method Not Allowed.

**Comment by bbangert** [comment]
That's correct, Routes has no built-in method to examine URL's that would be valid if the method was changed, as such failure to match is always 404. You'll need to supply a catch-all route for imprecise matches that returns a 405 if you want that behavior.
