### ISSUE TITLE
Keyword args to Route.__init__() are not saved properly

### ISSUE THREAD

**Issue by iafilatov** [bbangert/routes#17]
In https://github.com/bbangert/routes/blob/master/routes/route.py#L53 a new dict isn't created, and pop's later on modify both ``kargs`` and ``self._kargs``. This means that route parameters are lost when for example a list of routes is created and passed to Mapper.extend(), which actually recreates routes using ``route._kargs``.
I think is should be ``self._kargs = kargs.copy()``

**Comment by bbangert** [comment]
A substantial amount of tests all fail if that is copied. As such I believe its correct behavior the way it is.
