### ISSUE TITLE
Support protocol-relative URLs

### ISSUE THREAD

**Issue by vitorbaptista** [bbangert/routes#29]
Currently, it's impossible to create a URL like ```//www.google.com```. Looking into the code, I found out:

```python
# https://github.com/bbangert/routes/blob/master/routes/util.py#L259-L262
if not protocol:
    protocol = config.protocol
if url is not None:
    url = protocol + '://' + host + url
```

That could be changed to accept that if ```protocol == ''```, then we create a protocol-relative URL.

What do you think, @bbangert? I'd be happy to submit a pull request if you agree.

**Comment by webknjaz** [comment]
See #60
