### ISSUE TITLE
basic map.connect(None, "/{controller}/{action}/{id}") fails?

### ISSUE THREAD

**Issue by ac-** [bbangert/routes#34]
I have to use the basic mapping method for a dynamic controller and this simple documentation example fails (python3.2):

    from routes import Mapper
    map = Mapper()
    map.connect(None, "/{controller}/{action}/{id}")
    map.create_regs()

    print(map.match("/ctl/act/1"))
    >> None

Normally this should return:

    {"controller" : "ctl", "action" : "act", "id" : "1"}
    
Any help is appreciated, thanks.

**Comment by bbangert** [comment]
You're putting the path in the wrong place, and create_regs needs to contain valid controller's as a list. Like this:
```python

>>> map = Mapper()
>>> map.connect("/{controller}/{action}/{id}")
>>> map.create_regs(["ctl"])
>>> map.match("/ctl/act/1")
{'action': 'act', 'controller': 'ctl', 'id': '1'}

```
