### ISSUE TITLE
repoze.lru not installed automatically

### ISSUE THREAD

**Issue by pratikmallya** [bbangert/routes#35]
Is there a reason why there is no `requirements.txt` file for this repo? I'm using routes, but when I try install using pip, it does not install the `repoze.lru` package and my application naturally fails. I'm currently getting around this by adding `repoze.lru` in my own requirements file, but upstream would be more simple :)

**Comment by webknjaz** [comment]
Hi, 
there's actually repoze.lru in requirements: https://github.com/bbangert/routes/blob/master/setup.py#L52

**Comment by pratikmallya** [comment]
Hmm, that's strange. I wonder why it was not installed when I called pip. I'll close the issue for now, reopen it if I run into the same problem again.
