### ISSUE TITLE
middleware uses webob, which is not a declared dependency

### ISSUE THREAD

**Issue by fungi** [bbangert/routes#38]
```python
$ ../venvs/virtualenv/bin/virtualenv routes 
Using real prefix '/usr'
New python executable in routes/bin/python
Installing setuptools, pip...done.
$ routes/bin/pip install -U routes
Collecting routes
  Downloading Routes-2.1.tar.gz (179kB)
    100% |################################| 180kB 777kB/s 
Collecting repoze.lru>=0.3 (from routes)
  Downloading repoze.lru-0.6.tar.gz
Installing collected packages: repoze.lru, routes
  Running setup.py install for repoze.lru
    Skipping installation of /scratch/routes/lib/python2.7/site-packages/repoze/__init__.py (namespace package)
    Installing /scratch/routes/lib/python2.7/site-packages/repoze.lru-0.6-py2.7-nspkg.pth
  Running setup.py install for routes
Successfully installed repoze.lru-0.6 routes-2.1
$ routes/bin/python
Python 2.7.6 (default, Mar 22 2014, 15:40:47) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import routes.middleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/routes/local/lib/python2.7/site-packages/routes/middleware.py", line 5, in <module>
    from webob import Request
ImportError: No module named webob
```

Since you've defined webob in your setup.py tests_require and also manually install it in your .travis.yml your testsuite doesn't notice this, but it definitely appears to me to be an actual requirement.

**Comment by bbangert** [comment]
This isn't actually new in 2.1. webob was used by the middleware previously, the thought behind not requiring it was that not everyone may end up using the middleware, so requiring webob for the package as a whole would be overkill. Some folks get very picky about packages installing dep's if they're not absolute requirements, maybe that's changed in time though and I can add webob as a dep without ppl whining about it?

**Comment by fungi** [comment]
Thanks, description updated. And confirmed that we're separately depending on webob already in our software to work around this, so the bug report is mostly for completeness. It might be just as effective to "fix" it by documenting the optional dependency in the readme or something.

**Comment by fungi** [comment]
Oh, and it was added in 2.0 which we ended up blocking in our requirements lists due to issue #31 (so wouldn't have seen it until 2.1 anyway).

**Comment by webknjaz** [comment]
@fungi @bbangert 
Guys, I think it makes sense to add the dependency using `extras_require` and document possibility of installing extra dependencies.

**Comment by fungi** [comment]
Something like a "middleware" extra so that `pip install routes[middleware]` drags in webob? That seems a reasonable compromise (though install docs could benefit from updating to reflect this optional dependency either way).

**Comment by webknjaz** [comment]
See PR #59.
/cc: @fungi @bbangert
