### ISSUE TITLE
Need a new release 2.2 to get the Python 3 fix

### ISSUE THREAD

**Issue by haypo** [bbangert/routes#51]
Hi,

My pull request #44 was accepted, but there is not release including this fix yet. So I'm still unable to install Routes on Python 3 (because of the new cache of wheels of pip 7). Please release a new version including this fix. Thanks ;-)

Victor

**Comment by CyrilRoelandteNovance** [comment]
Yeah, a Python3-compatible release would be really nice, especially for OpenStack.

**Comment by haypo** [comment]
> Yeah, a Python3-compatible release would be really nice, especially for OpenStack.

At least OpenStack Neutron is blocked by this issue.

**Comment by bbangert** [comment]
Released. Sorry bout the delay.

**Comment by haypo** [comment]
Great! Thank you.
