### ISSUE TITLE
Routes 2.3 changes API for SubMapper.connect()

### ISSUE THREAD

**Issue by tbreeds** [bbangert/routes#64]
In OpenStack Neutron (and other projects) we call SubMapper.connect() with a single argument.  See
https://github.com/openstack/neutron/blob/stable/kilo/neutron/api/extensions.py#L293

As of Routes 2.3 this now generates a traceback. See 
http://logs.openstack.org/95/293195/5/check/gate-tempest-dsvm-neutron-full-kilo/d5c1fd1/logs/screen-q-svc.txt.gz#_2016-03-28_21_10_22_791

This is because 0a417004be7e2d950bdcd629ccf24cf9f56ef817 made is mandatory to pass 2 args into connect

https://github.com/bbangert/routes/commit/0a417004be7e2d950bdcd629ccf24cf9f56ef817#diff-b54de741c3f86d76eb4bce4a223054aaR168

Was that patch a deliberate API break?
Is there any possibility of releasing 2.3.1 with the old behavior?

**Comment by tbreeds** [comment]
For completeness the OpenStack bug is: https://bugs.launchpad.net/neutron/+bug/1563157

**Comment by bbangert** [comment]
@tbreeds can you confirm that PR #65 remedies this issue?

**Comment by tbreeds** [comment]
@bbangert Yup works for me

Thanks everyone

**Comment by bbangert** [comment]
Closed by #65

**Comment by bbangert** [comment]
I'll get a new release out tomorrow.

**Comment by dims** [comment]
Thanks @bbangert

**Comment by bbangert** [comment]
2.3.1 has been released to pypi.
