### ISSUE TITLE
escaping colon as part of the path

### ISSUE THREAD

**Issue by paulo-raca** [bbangert/routes#79]
I understand it's very non-standard, but I need colons as fixed parts of my mapping

I'd like my code to look like this:
```m = Mapper()
m.connect('/id/foo:{fooId}'), controller='getFoo')
m.connect('/id/bar:{barId}'), controller='getBar')
```

Right now I'm getting the error `bad character in group name '{fooId}'`

Is it doable?

**Comment by webknjaz** [comment]
@paulo-raca try putting `%3A` instead of `:`

**Comment by paulo-raca** [comment]
Thank you!
