### ISSUE TITLE
Duplicated code of URL generation

### ISSUE THREAD

**Issue by marc1n** [bbangert/routes#8]
In util.py module there are url_for() function and URLGenerator.__call__ method each has over 100 lines of complicated code which does almost exactly the same thing. It's ugly! 

One of bad consequences of this is that it is hard to answer if I can safely replace  "pylons.url(...)" (URLGenerator instance call) with "paste.url_for(...)" (url_for function call)  in my pylons application?

**Comment by bbangert** [comment]
It is ugly, however they're just different enough that I can't easily consolidate them. I would just switch them, and verify with tests or looking at the page if things have broken.
