### ISSUE TITLE
Escaping special characters such as the colon

### ISSUE THREAD

**Issue by aib** [bbangert/routes#82]
There needs to be a mechanism to include routes with the special characters such as `:` in them. The workaround in #79 does not work with CherryPy, for example.

https://github.com/bbangert/routes/blob/9cd647a12f38de5082f4c052c2f355858b65f724/routes/route.py#L157

**Comment by webknjaz** [comment]
Why doesn't it work for CherryPy?

**Comment by aib** [comment]
I'm not too familiar with Cherrypy's workings, but using the `RoutesDispatcher`, the `%` seems to be taken literally, i.e. a `/foo%3Abar` route results in just that (`/foo%253Abar` on the browser.)

**Comment by webknjaz** [comment]
I'm not sure, needs a reproducer. It might be that alias with `@cherrypy.expose` is needed.

**Comment by aib** [comment]
Reproducer?
And what do you mean, an alias with `cherrypy.expose`? I'm not using `cherrypy.expose` currently.

**Comment by webknjaz** [comment]
Reproducer == minimalistic piece of code demonstrating the problem you're seeing so that others could verify whether it's reproducible locally.

Why don't you use expose?
Alias example: http://docs.cherrypy.org/en/latest/advanced.html#set-aliases-to-page-handlers

**Comment by aib** [comment]
Reproducer:

```
import cherrypy

class Controller:
	def do_test(self, *args, **kwargs):
		pass

controller = Controller()
dispatcher = cherrypy.dispatch.RoutesDispatcher()
dispatcher.connect('test', '/esc%3Aesc/:var/foo', controller, action='do_test')
cherrypy.quickstart(controller, '/', config={ '/': { 'request.dispatch': dispatcher } })

$ curl -fsw '%{http_code}\n' 'http://127.0.0.1:8080/esc:esc/42/foo'
404
$ curl -fsw '%{http_code}\n' 'http://127.0.0.1:8080/esc%3Aesc/42/foo'
404
$ curl -fsw '%{http_code}\n' 'http://127.0.0.1:8080/esc%253Aesc/42/foo'
200
```

**Comment by bbangert** [comment]
PR for this was merged.
