### ISSUE TITLE
Invalid escape sequences when running under py36

### ISSUE THREAD

**Issue by stmcginnis** [bbangert/routes#84]
Python 3.6 is more strict about allowing escape characters in normal strings. This most often occurs with regex strings and results in warning messages such as the following:

routes/mapper.py:410: DeprecationWarning: invalid escape sequence \.

In most cases this is just a matter of changing from a regular string ("\") to a raw string (r"\").

**Comment by bbangert** [comment]
@stmcginnis is this still an issue? a PR was merged that supposedly addresses it.

**Comment by stmcginnis** [comment]
Thanks for checking @bbangert. I will check with the latest routes release and see if I still see any issues (once I remember where that was that I saw it).

**Comment by stmcginnis** [comment]
I upgraded to the 2.5.0 release and that did address the majority of warnings I was getting. Looks like there was just once instance missed though.

I've put up pull request https://github.com/bbangert/routes/pull/98 for that last case. That is all I found in my logs, so I think that should take care of it.

Thanks!

**Comment by bbangert** [comment]
Closed by #98.
