### ISSUE TITLE
About Version 2.4.1 

### ISSUE THREAD

**Issue by gange111** [bbangert/routes#90]
Update the version. The current version has not been updated for more than three years. 
I think it's not active at the moment. If it goes on like this, it will affect the usage. Thank you.

**Comment by bbangert** [comment]
Indeed, given the various PR's merged since the last release perhaps its time for 2.5.0 even.

**Comment by bbangert** [comment]
2.4.1 was released afaik, pypi claims it was. The changelog wasn't updated though.
